# Generated by Django 2.1 on 2019-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Pages', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='category',
            name='slurl',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
