# Generated by Django 2.1 on 2019-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190219_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slurl',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
        ),
    ]
