# Generated by Django 2.1 on 2019-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='maxresdefault.jpg', upload_to='profile_images'),
        ),
    ]
