# Generated by Django 2.1 on 2019-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20190522_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/profile_images/piter.jpg', upload_to='profile_images'),
        ),
    ]
