# Generated by Django 2.1 on 2019-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20190531_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/profile_images/a5ca62142c9628b9c75fad043b91d1a3.jpg', upload_to='profile_images'),
        ),
    ]
