# Generated by Django 2.1 on 2019-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20190612_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.CharField(default='Vladimir Putin', max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='desc',
            field=models.TextField(default='Лучший учебник по построению свободного и прогрессивного государства'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, height_field='200', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='slurl',
            field=models.SlugField(default=116, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='year',
            field=models.CharField(default='1949', max_length=4),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='1984', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/profile_images/piter.jpg', upload_to='profile_images'),
        ),
    ]
