# Generated by Django 2.1 on 2019-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20190612_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/profile_images/a5ca62142c9628b9c75fad043b91d1a3.jpg', upload_to='profile_images'),
        ),
    ]
